### ISSUE TITLE
Create header

### ISSUE THREAD

**Issue by s-abdale** [cherryontech/burnout-buster#22]
**Acceptance criteria:**
1. Create a header that replicates the Figma design
2. Add the header to the quiz page and results page

**Bonus work:** N/A

**Priority:** Low

**Size:** Small

**Comment by vasconsaurus** [comment]
references:

![Image](https://user-images.githubusercontent.com/87862340/222940488-34766f5f-7487-4207-8e7c-fad5795c4b1f.png)
![Image](https://user-images.githubusercontent.com/87862340/222940487-3175f6cc-eee4-4044-b516-ca70e0653455.png)

**Comment by s-abdale** [comment]
Note: Connect with design to discuss moving back button out of the header and inside the quiz
