### ISSUE TITLE
Create results page

### ISSUE THREAD

**Issue by s-abdale** [cherryontech/burnout-buster#24]
**Acceptance criteria:**
1. Create a static page with at least one result which replicates the Figma design

**Notes:**
- Work inside the quiz.js file (src>pages>quiz.js)
- Add styling to the globals.css file _or_ make a new CSS file for the quiz page

**Bonus work:** N/A

**Priority:** High

**Size:** Medium

**Comment by vasconsaurus** [comment]
references:

![Image](https://user-images.githubusercontent.com/87862340/222934996-1c0a2bf3-cdd4-4155-9eed-3f29ee7e3a75.png)

![Image](https://user-images.githubusercontent.com/87862340/222934995-0c7da0f4-2a51-4f3f-a237-fd77d10a343e.png)

![Image](https://user-images.githubusercontent.com/87862340/222935000-be98c350-68ff-40af-b893-6816395c1979.png)
